# Generated by Django 3.2.16 on 2023-01-06 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_article_tttt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tttt',
        ),
    ]
